[advisories]
ignore = [
  "RUSTSEC-2025-0057", # fxhash is no longer maintained, tracked in https://github.com/filecoin-project/ref-fvm/issues/2221
  "RUSTSEC-2025-0141", # bincode unmaintained, transitive dep via bellperson/filecoin-proofs
]

[bans]
multiple-versions = "allow"

[sources]
allow-git = [ "https://github.com/filecoin-project/builtin-actors" ]

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "MIT",
  "NCSA",
  "Unlicense",
  "MPL-2.0",
  "Unicode-3.0",
  "Zlib",
]
