[package]
name = "fil_syscall_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_ipld_encoding = { version = "0.4.0", path = "../../../../ipld/encoding" }
fvm_sdk = { version = "4.0.0-alpha.4", path = "../../../../sdk" }
fvm_shared = { version = "4.0.0-alpha.4", path = "../../../../shared" }
minicov = {version = "0.3", optional = true}
actors_v12_runtime = { package = "fil_actors_runtime", git = "https://github.com/filecoin-project/builtin-actors", branch = "release/v12" }
multihash = { workspace = true, features = ["sha3", "sha2", "ripemd"] }

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build

[features]
coverage = ["minicov"]
