[package]
name = "fvm_example_actor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
fvm_sdk = { path = ".." }

[profile.release]
lto = true