[package]
name = "fil_integer_overflow_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_sdk = { version = "4.1.0", path = "../../../../sdk" }
fvm_shared = { version = "4.0.0", path = "../../../../shared" }
fvm_ipld_encoding = { version = "0.4.0", path = "../../../../ipld/encoding" }
fvm_ipld_blockstore = { version = "0.2.0", path = "../../../../ipld/blockstore" }

anyhow = "1.0.71"
cid = { workspace = true }
serde = { version = "1.0.164", features = ["derive"] }
serde_tuple = "0.5"

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
