[package]
name = "ipld_amt_fuzz"
version = "0.0.0"
authors = ["ChainSafe Systems <info@chainsafe.io>", "Protocol Labs", "Filecoin Core Devs"]
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.1", features = ["derive"] }
ahash = "0.7.6"
itertools = "0.10.3"

cid = { workspace = true, default-features = false, features = ["serde-codec", "arb", "std"] }
fvm_ipld_amt = { path = ".."}
fvm_ipld_blockstore = { path = "../../blockstore" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[workspace.dependencies]
cid = "0.9"

[[bin]]
name = "equivalence"
path = "fuzz_targets/equivalence.rs"
test = false
doc = false
