[package]
name = "fil_gas_calibration_actor"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fvm_sdk = { version = "3.0.0-alpha.24", path = "../../../../sdk" }
fvm_shared = { version = "3.0.0-alpha.20", path = "../../../../shared" }
fvm_ipld_encoding = { version = "0.3.3", path = "../../../../ipld/encoding" }
cid = { version = "0.8.2", default-features = false }
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.51"

[build-dependencies]
substrate-wasm-builder = "4.0.0"
