[package]
name = "cgobs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cid = "0.7.0"
multihash = "0.15.0"
blockstore = { path = "../../../lib/blockstore" }
unsigned-varint = "0.7.1"
