[package]
name = "fil_events_actor"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_ipld_encoding = { version = "0.3.3", path = "../../../../ipld/encoding" }
fvm_sdk = { version = "3.2.0", path = "../../../../sdk" }
fvm_shared = { version = "3.2.0", path = "../../../../shared" }
serde = {version = "1.0.145", features = ["derive"] }
serde_tuple = "0.5.0"

[lib]
crate-type = ["cdylib"] ## cdylib is necessary for Wasm build
